### ISSUE TITLE
Define Components

### ISSUE THREAD

**Issue by MartinTrinkl** [dih2-rowa/programhandler#2]
# Overview
List of the components which are needed for the Programhandler. The list is made here but every Part gets his own issue. Link the Issue to the list. 

## TODO
- [x] Define and describe needed components.
- [x] Define and describe input and output data which are used from components.
- [ ] Define und discribe protocols and api used for communication between components. 

## Components
-  #3 
-  #9 
-  #6 
-  #7 
-  #8
-  #10 

## Architecture 
![image](https://user-images.githubusercontent.com/102011176/167640892-996d10b8-0df6-48a8-bb8e-8e81a364b382.png)
